#!/usr/bin/env bash
echo "If you dont have /root and /boot/efi, create it with gparted"
read -p "Enter your /root:" ROOTPART
read -p "Enter your /boot/efi:" EFIPART
read -p "Enter your username: " USERNAME
mkdir -p /mnt/bistroot
mount $ROOTPART /mnt/bistroot
mkdir -p /mnt/bistroot/boot/efi
mount $EFIPART /mnt/bistroot/boot/efi
pacstrap /mnt base base-devel linux-lts linux-lts-headers xfce4 lightdm lightdm-gtk-greeter grub efibootmgr networkmanager network-manager-applet
cp /usr/src/installscript2 /mnt/bistroot/usr/bin
sed -i "s/USERHERE/$USERNAME" /mnt/bistroot/usr/bin/installscript2
mount --types proc /proc /mnt/bistroot/proc
mount --rbind /sys /mnt/bistroot/sys
mount --make-rslave /mnt/bistroot/sys
mount --rbind /dev /mnt/bistroot/dev
mount --make-rslave /mnt/bistroot/dev
mount --bind /run /mnt/bistroot/run
mount --make-slave /mnt/bistroot/run
chroot /mnt/bistroot "/usr/bin/installscript2"
